apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-dns
  namespace: cert-manager
  annotations:
    kubernetes.io/description: "Sealed acme-dns credentials for DNS-01 solver."
spec:
  encryptedData:
    acmedns.json: AgBle3dfNsYdAOhwldcRYVfeOsjFe0rPOZsqpzgggP21toVrDUs1kT1WU0DF7F1P2KaCNcVB1QOepSVjZCFdBfL26hodu8VpZbnyaFVwmjwdKrhfNAYCVxaozLeeYwBfMeyAfYgRLfMRDQE/1K98jrL5kzezIutUOo0khNtWtqdVd4kHAsBrGTrov63zecriIRp5FzfDJvrpwarMOV26ssKldJdF+gA1XFMumDdhmNAXjJCf357Hmz6gJH6OB7bFPe8etEgqNSIU4QXAlcVycJbKUwxynq1cuThWhxjTZIjOOPN1o5SdXEUS4YuWy3ZFhVL8ZvfyDHmIV3QHE7lqH4OqD3miwVRuyovUUDJKuNNIyGDlk3WhA+3epMkIFzu3jsTmTiQXrif3KXs40dJmj5nZWBsp7mwmMXx27wVeL66PQO0dkUKd6W+jw7spFkrjJiZi5+uzUVJzPmD2PwMSpmH6t0JozSX+8XtwmxWaUOa+gRcOFYiTPcrA1xUrA5Wq/8gaMZmOJ6Oyx7RSy8RL2YBbCbIahfM7jzciP5BP2JncK7wi79dgyTHtf9e4EE3yFR3e6bu23mwfU5f2dKT93a5H0o4qQMQZXXw2XiRm8qM+CK83xAHD+CtCjG1+HH+UJNOW7AyUBqt7P+JiQt/NbB0N3mGox47iGPS4vwXfCxiftQmDR5U0+rYqInvHFJnrr3xFbXQEvlRCE15dgs96WWTudGkIO2t4YpYbabnCkVScO2jRKSk2sMRrfqIc2VD/rXzcXjYhDELbE1MCkOCACSGS3Rzlhmv35/Y7G0GJXbKkQlzfcsl1/MUHCYcRgJHxosNwI89pMyUkyFWZwRLbDhQEQjE+tWzueBDd+kCQWDLMzD6Fw+nvr6JM8sgITkGpRaff5/OLIFTGbx/DExMK22zRGZ8mTSLPsBCFtwEUwC7OBM1XmMzLYk6QA7uDZI3vIAl1hM0trFUHZUKoR534533xcTdo+MuRX1/sPs+IcVWcfBHD9GhJVXWg5QAhTdgPI5T7JARwr/BsxE+2R1tXF8m5gsV7s8S2xMWsKt6vkfZEO8rLF9yeh40lakrU59umIrHSvxSB
  template:
    metadata:
      name: acme-dns
      namespace: cert-manager
      annotations:
        kubernetes.io/description: "acme-dns credentials for DNS-01 solver."
    type: Opaque
