apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: operator-oauth
  namespace: tailscale
spec:
  encryptedData:
    client_id: AgBXZdtOPbFTnUjduSa5d6NOseiJq/77KE4hPB0vzNQFP+L/mOg6OMsY/rEXxusCJ1CM/bqTQKBnwDSArxOxFK9FoE/Z+fjjmr0k1PoO1gNIJYDTk/BRi8aCQ0Wit0yi0CYJ4pgyV9cpNS1eHepQKecOFSD11JXsY1UbOyubS6oSA0dcLBPDEjD1YUnQb6XtPOxHkJrv4Jgw4hj/yRLZonHrA350lsJVU5WaHGfwdIHAt5x44Ks054x3VbDfPB3Xxu1tzGPAtBBd137RuMCRfX6Rfhy0ynCSZp2O9v6eOZh6hXk0eO7ODe6zSmsvjINhLEu+N+xH1qwz4bNV7SgUoepB7+L2NvCwPOsNjGngUfil62y5+tYK+Ctk0SZoOjRo/erbLd9r9VrzuScRcKoy3Y3EtEdYgLo6M9bS6D3RLppRpz1ELUYAKS0cU3JLSMs2eDp/CXzrtvsjYI/RV3FlhOoKxLmwv3rb/08Hd4hivyfdsXGxtgK9FWyAC+S5WggZmxLiH3kj9cjxI37yGv5lMv/1P2xUUvJoNwtC3b/cAkcuEp/2YA1a3w+F6hfc46xK36QpvnDgZjdNzqk/1VYq8wH0VxemayI5NZlLVdAHu0MW+MjRo5n02mfeNpaG8813rWjhcrkkXGCeOF+Q0rZ6EhGr9K1AzR96pIfbaVtSBgjjAy04HbDiR+LIqg3xXDWlQKzTVl1UGKNAtoB2GyaK37WDvw==
    client_secret: AgBBv1qegSSmeJ3MuvjPeOg/XPLyzBsXAmXmBAvxA5WCPq7pFUandvhqCUZLj7hJJzAJVattJpNhz8q+SILF6UtOeiGEKFKQsKqDx3oVW8EY86Pi34GEKG8ksFGAPDYOJNskqxFiyaCgqFX+UYzto11FoKrLatulpw4YkoWy9Th8KirV87q+6OKS2ms/kZka3mSlNaovwt/0MjimQG/eqmx+8fdAcQvAYov9eWJUT2Hb7gFnp62TiiI1dLKsok16XKZAXdh6+zq/Dm8893w73g5QPYKt/+iADLg7GHTyQ/UZ0vt1VTrVI0WZBVFck2CNcGGGmorYdtsgB586nKhDbzBWnmnbTw0hwc2/q3szMfE0s6hLxtj+0mMsmeM6Tl6ILW9cJyUqx9wLcjvUUW+i1mYVfeVYyEbAifWqC9ny+vwFoTdOYuXoeBsxm+8NQpWipIVP92IoAG9mTAQiy7wB2rNCgvZeK+bDYm10nSaj10qpbZo2b4snUPNEUDo36Z7jE8YxxAx9Q5cUDiuRPeI1DeL2wwtp+ziMk8YDZwo6tp0U+SspExO/ihEKXJR2G6nNUdFWUrjNRkRxKVgKQ9oIdNP3tJ90sP2e+f72Lhy6btM0ZUNn6X6yFdkIifzdCS9cp49M86ilsQ2icpkAmhdUyuOu+CJDSjSaDjJ8erttn6+BsSiuuUy+yErIDDctQKfWwCFXDwpVBOtHzxAGJZaKqolwnaM6ccZwjREzcj+jYbQiQDyaZcNGiyjuaWO8zJGSaBXyxlBB0kC1nU0yeTWZvtQ=
  template:
    metadata:
      annotations:
        kubernetes.io/description: Sealed secret for Tailscale OAuth
      labels:
        app.kubernetes.io/component: oauth-config
        app.kubernetes.io/name: tailscale-operator-oauth-secret
        app.kubernetes.io/part-of: tailscale-operator
      name: operator-oauth
      namespace: tailscale
