apiVersion: v1
kind: Service
metadata:
  name: wallabag-redis
  namespace: wallabag
  labels:
    app.kubernetes.io/name: wallabag
    app.kubernetes.io/part-of: wallabag-stack
    app.kubernetes.io/component: cache
  annotations:
    kubernetes.io/description: "Cluster-internal Redis service for Wallabag."
spec:
  ports:
    - port: 6379
  selector:
    app.kubernetes.io/name: wallabag
    app.kubernetes.io/component: cache
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag-redis
  namespace: wallabag
  labels:
    app.kubernetes.io/name: wallabag
    app.kubernetes.io/part-of: wallabag-stack
    app.kubernetes.io/component: cache
  annotations:
    kubernetes.io/description: "Redis cache for Wallabag."
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wallabag
      app.kubernetes.io/component: cache
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallabag
        app.kubernetes.io/part-of: wallabag-stack
        app.kubernetes.io/component: cache
    spec:
      containers:
        - name: redis
          image: redis:alpine
