apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: wallabag-stack

resources:
  - namespace.yaml
  - secret.yaml
  - db.yaml
  - cache.yaml
  - app.yaml
  - ingress.yaml
