apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wallabag-secrets
  namespace: wallabag
  labels:
    app.kubernetes.io/name: wallabag
    app.kubernetes.io/part-of: wallabag-stack
    app.kubernetes.io/component: config
  annotations:
    kubernetes.io/description: "Sealed credentials used by Wallabag and MariaDB."
spec:
  encryptedData:
    MYSQL_PASSWORD: AgAa8hjVA4umEnoW5VsjwOrUGw1tFKABzwRFx8DlseCHpScn+F7P21z++KPPMlaLEuW9CZOXSbjb5qk0PZv2VT8dAAKLkGkcFYwQ0GhZu4njG0/A1A/Gd8AViexH5DWHkCsvEBTY755GUcUl5kKT1X35GolGNkD5GsUrERjDe/4cHayZbooC3KH64YC8hiBM91ol4cXo9zdgf528VcpDF4wdp+INxNAxazfluGW07q1a0vwodBqnVgeSu47Z1oCy6ZPXRX6Ogo464084Uf5emCvDn8J9CYgrSdmLeT/Vy64sMNz1tveaA0q4lBJWv4NKjR8RNmXKuOqIaFak+UIgnz1gxWKMzUIZrKACs4Bhad5XdHcfVMU4dIBJ3VW+smNcdtpZnmZTpYH/i7xSfh8tTz8Nmz5u0r6AhCAmE2nB/E/f5nfhKUTqEEUz8DfaStQ4CzIFDyjOTC/7en7vGxweC4kiojxrspPCOs42bDM3TMIUr1YnYY/BPiqtxvf7gT7++CX3QndnShLA+EQExWd31+Qyrbg/JG2qA+r54L6SpuLThaQx9l5wH+M9ReDOm0Pnr4/xJKmy+jIRlDc1P7vYSOlHNTzLR9YfZ1XRCOCUlxyIvbOooFwfddLa0zKhFNEwW+wZPeZiYbSdJP6tzR9jJ2zMawqYPYb0lfH7Z9/ZEsxN/k+W7GF2gh5T/oHY0aEW72i1RGHDrFfz0Gs=
    MYSQL_ROOT_PASSWORD: AgBJlnBFOocws8S/Pf2cEqNzy+cHcfjZOL9wy7/jZAgGN75yvkXmJNJ2XIPhAFKc5l4MjRy2qGTitg75OJWBDT11JGWxPu1a609WCbfcvBToqJlwjtrQIKzLSb85+YshXN+hx8l2zS5H901EEErlNsMX7biRm/ENFkk0/TywLiX62EogHtr9G97uWHeOdIHdpRs05NTZKZ/M6W4chnP20zG7TzNexAK7i2nTGIQM7gCu9/vG6tD2y2x/WXK6/JKGNjsv/O85tJHKRrQS6rZPuZAgXtQi585lFjpdB4zSxShgWyN/iZMbCdmJcgKR5DMyAjgw9W3qWJCL8JDJAL1MxyhwNdiQPJOlxVdIQix9ngwmPDsU9yTsjS+At0v7VFtyxavMAb8bnO9nSimo8Et5VHSSQrfrLYYPOF8noXY0GhQldcmJZp7XXCU1P9lNo4tuzBxoBucaI8Qe/wECGuuB/gJLwjTxSeradgKBoitNiDJ3msM9WowjcLv0YK9IVLA9KG/4Hc4qRFX0zsRnygLHydJ7INx1qHdyf5LWhKmghk7MvEkQzB6wMf1K0pY83YdbrxoXr6QwvJnsHvCGJPr8vQsPqdoGodqzKKKIZ6JaisxTa6O6XAVbZS7wxvK4BRPC8KGyW8YX/7nU8eq0fEEFVtHwYu7ZIXEIDpoh1dDORg6dbhes7Ugf9L6gIDhn5DFwklkOzDAm9fh85MI=
  template:
    metadata:
      name: wallabag-secrets
      namespace: wallabag
      labels:
        app.kubernetes.io/name: wallabag
        app.kubernetes.io/part-of: wallabag-stack
        app.kubernetes.io/component: config
      annotations:
        kubernetes.io/description: "Credentials used by Wallabag and MariaDB."
    type: Opaque
