apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform-cert-manager-config.yaml
  - platform-cert-manager.yaml
  - platform-sealed-secrets.yaml
  - miniflux.yaml
  - wallabag.yaml
