apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: miniflux-secrets
  namespace: miniflux
  labels:
    app.kubernetes.io/name: miniflux
    app.kubernetes.io/part-of: miniflux-stack
    app.kubernetes.io/component: config
  annotations:
    kubernetes.io/description: "Sealed credentials and connection settings used by Miniflux and PostgreSQL."
spec:
  encryptedData:
    ADMIN_PASSWORD: AgCCQhqUb0StZwG231188l/HNawy/EILaDhdqcj/Kp4jxUJpVwzYz0EotVN6CtZ44LT7onrtyi3qPPNGZtKymt/hATTi63rSy6cng/hZPKwd0ij2jdQ18gwwk0RHuitp/qTqJqn3bJwXkJ/yv5En9Vr4AGQjCAjhXzS2IRup2Sy5BUsQiKR6mllxO3gLwV6HRLoIkkB0UyTc0Fs6HOxhlh0Gmws0LDE62FFKcn0jQHQJ0xw9KQvFIgUoW/wVSEhc2yUHdqFrz1rELhDp4owvZMrLxZFbMsnp1nlini1RDMa+Gj3tnvbXPlW20NOaErbX9O40OgckGtMKr4ZWTmwUk9Nf9UOhieBgj/+YvK31r9nCBTJkhaVLnI43N5p3OA74oujGlxfY7Yv8cEHGVbOj7Fvf7eNAcSrUbAyjfchNFbmugyz+hQk7bsHJbufO2ANGz03e6FqzlO4OmkPJS1DtN8W630J/ySQf3MSUKg/ZqvavBfUfpwQm/LOMrFKC+VgYsBVHCmonZ+LfR09viYlxDbEMf0oTCb/Apsz0K1kueo63ZU1X2Wk6NfSPHaKuyPP5xmNOE5CI/aanRxTUg1fdET7pevzVzYsN7uxHPEG7XnsaJ8zInDP46NxQZqAfN1eeHCpSTtlmTY8GYkG2WKt1buvnf2igzp7uN1f45AKmnXGOfl6Ba31b0UaK4Q1A2QrAUtjFlSF1TuU=
    DATABASE_URL: AgCnfrGlyHGu7OHMm2QUC3d4QTWoaOlrOaKXe1lHE9dVNWeE9CtXFIlOHjrOjqZ4GUWJQiJumwIz+7/bkGgNZstr5Vr1fyt6YI7OoyB+7t7dd4zUX09+3RSYUjkbwNTkYcLGyUPAeg46EYSzLym3+SaHrILFcwSDZ89eEBAIqLXNUERZfndCFHaFY2QTtjJyTnZhIpiF4sq1YyrKcb+mGbZuAnehMxnvkNijr8bmq/w8qIphoJorHJj+uQS/koL61BKJIau1Vpumcu0yLAVG19mZstUMD26w6oXw///WOYTT4k8kfPm5eNnuj3fjk9wVpR+BKJAsp4DCq4B2JesupQ6sK60ATu/sBLlj6/jMdv3vR4ZFmz3vlXc9wo7HUjJPUGkrSoJTLEJ8Y/sjqWRcDRs/9WDMKerXHk9sf1w6w/doInisaiU96+Gt9GmEHzTNDeNZ0Syy4Fbl/ivZi0+RHLtUpJ+k24u29mp6TZMW+rLddJyegQzT+/pQNOmjrZBC0yw5mrJQ6FwunMEH+hqrMg4S6sjz+gXWmfTdgUwgRBPH6Pi+rlyRS71ngUPXf2YYKnmqN41KwOXNipmPvtbQaHTbaUqT9bNkPvjEXWFdduZIk2xp41+pWYXTXu5J/Pf1sTMrV8fV5gp38sLkUoa8VQnmoTkH5LOtBmspnRlTe3kZ0mUGS6Rj0k8X6PbKyrZpGiyuKaAcrvjn/vKvHa5/Eg6VWKdlMClYS13ZChIWsUl371UvtjC8q2x4ZK0l7n/nQz//PvJ6wXXkSKs/EpNd4Us=
    POSTGRES_PASSWORD: AgAQIRHvdtW7o1cOI551kXorf4SocjDNmxi+6lYZqvJLd33Vp8ntjJOmXkvqScMCxLirVYBwkfOXkq5iBGIAb9PkUvN9Pg41KxlDsaq6sfFPL0seHqQswJMWhlUYdWO3le7IRkx49tQCK4EUoEF1ZeCF3xlAUjUU9REA3mhAvl8rjmr4QXosvNFNbwMoLiybrt/F7mb6AqaAwtCwz5ndELm+5kEBUlWWJkDRkELYcW19zm1eyv568MByq3Z5qjij4x0iszq7sKpeytQhu6sZEPKpC2o1yNe9Y9JH9zrFpOoaovgFvcbEx2fuwqM8/7XnuVmrf5KTk+U+ZkB2N9yH9AVKnaU+csmYeAzxOC0HJFRFdW1Lpt5NzAq+AFqqVL2PU/rcp+17DDQ+qFDFmLEcnj5bCQ1zZfQwNwTOa/YNx/HTn2cFhHg0SeRHuFPaz4z4Wv+6Qw9mD+CAu4BHS2YFm8sKnVCfFFayfvsqhFgExv09EmFTUonffpiSYN825Qiyz3Dre7vsOKZ41/o0gDMEoFoeLoA1HrJeVpRu9IcGfQssqhfv6+j3XW+HXRkU4xxGhvJKJl6jY8BttWqLCHAggk+lSdSqNNbG4PfRt480CGG8XAIZkXmur/5Bg5Hpgz86oxu7v/OqMHRVno0caMoRJaCIQG8EqZzvyJzEUdLLhjxABegXNY/PKub8Z83mt/wtqRPhi799yE4=
  template:
    metadata:
      name: miniflux-secrets
      namespace: miniflux
      labels:
        app.kubernetes.io/name: miniflux
        app.kubernetes.io/part-of: miniflux-stack
        app.kubernetes.io/component: config
      annotations:
        kubernetes.io/description: "Credentials and connection settings used by Miniflux and PostgreSQL."
    type: Opaque
