apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootstrap-sealed-secrets.yaml
  - bootstrap-cert-manager-install.yaml
  - platform-cert-manager-config.yaml
  - miniflux.yaml
  - wallabag.yaml
