apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallabag
  namespace: argocd
  annotations:
    kubernetes.io/description: Wallabag ArgoCD app
spec:
  project: lcat
  source:
    repoURL: https://github.com/lc-at/-kates.git
    targetRevision: main
    path: apps/wallabag
  destination:
    server: https://kubernetes.default.svc
    namespace: wallabag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  info:
  - name: Wave
    value: '3'
  - name: Description
    value: Wallabag bookmark archiver with MariaDB and Redis. Runs in sync wave 3.
  - name: Ingress
    value: https://wallabag.lcat.dev
  - name: Depends on
    value: platform-cert-manager-config
